[sidebar]
title = "Navigation"

[[sidebar.links]]
name = "Home"
url = "/"

[[sidebar.links]]
name = "Blog"
url = "/blog"

[[sidebar.links]]
name = "Github"
url = "https://www.github.com/hyprborey"

[[sidebar.links]]
name = "Reddit"
url = "https://www.reddit.com/user/Hyperborean-8/" 

[[sidebar.links]]
name = "Blue Sky"
url = "https://bsky.app/profile/hyprborey.bsky.social"

[[sidebar.links]]
name = "Home"
url = "/about"


